component: scf
name: scfdemo
org: test
app: scfApp
stage: dev

inputs:
  name: Robot
  src: ./src
  runtime: Python3.6
  region: ap-guangzhou
  handler: index.main_handler
  environment: 
      variables:  
        secretid: AKID30mNrAFaJuVwERoLfqroaCsOmBQUcEr7
        secretkey: J8uVDnEUYRAoLWEsgNrB61fHm9XkmkYA
  events: 
      - timer: 
          name: timer
          parameters:
            cronExpression: '*/5 * * * * * *'
            enable: true
